apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
    env: testing
    dc: IN
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 32100
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  labels:
    app: web
spec:
  accessMode: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcon
  labels:
    app: web
spec:
  replicas: 1
  strategy:
          type: RollingUpdate
  selector:
    matchLabels:
      app: web
      env: testing
      dc: IN
  template:
    metadata:
      name: devcon
      lables:
          app: web
          env: testing
          dc: IN
    spec:
      containers:
      - name: web-con
        image: vimal13/apache-webserver-php
        volumeMounts:
          - name: web-vol
            mountPath: /var/www/html
      volumes:
      - name: web-vol
        persistentVolumeClaim:
          claimName: web-pvc
