FROM centos:latest
USER root
RUN yum install wget -y
RUN wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
RUN rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
RUN yum install java-11-openjdk.x86_64 -y
RUN yum install jenkins -y
USER jeknins
ENV USER jenkins
USER root 
RUN yum install git -y
CMD ["java","-jar","/usr/lib/jenkins/jenkins.war"]
#kubernetes
RUN curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x kubectl
RUN mv kubectl /usr/bin/
RUN mkdir /k8s_crt/
COPY client.key /k8s_crt/
COPY client.crt /k8s_crt/
COPY ca.crt /k8s_crt/
COPY myinfo /k8s_crt/
COPY myinfo /k8s_crt/.kube/config
